### ISSUE TITLE
bug: f-string is used incorrectly

### ISSUE THREAD

**Issue by ChenXu233** [Shadow403/nonebot_plugin_lolinfo#8]
# 出错点：

https://github.com/Shadow403/nonebot_plugin_lolinfo/blob/8887d59e2466202aa08f25ce4b35d894483b42e0/nonebot_plugin_lolinfo/utils/util_urlpath.py#L32-L34

# 出错原因

在以下代码中，使用了f-string的语法，但是字符串和字典调用同时使用了 “ 双引号。
```python
v1 = f"{config.lol_html_str}{rOrg["runelist"]["rune"][v0]["icon"]}{config.lol_html_end}"
```

在python3.13中，该语句能够正常运行。
但在3.13以下的版本中，均不可运行。

# 解决方法

1.  修改pyproject.toml，将python依赖版本增加到3.13以上

https://github.com/Shadow403/nonebot_plugin_lolinfo/blob/8887d59e2466202aa08f25ce4b35d894483b42e0/pyproject.toml#L10

2.  修改f-string中的代码。

```python
v1 = f"{config.lol_html_str}{rOrg['runelist']['rune'][v0]['icon']}{config.lol_html_end}"
```

## 推荐使用第二种方法，能够保证更多用户能够使用。

**Comment by ChenXu233** [comment]
另外，正常的pr接受方法是在该pr中进行merge，而不是拉取文件后手动commit。

在pr的特性update了之后请关闭pr，避免pr长期挂着。

**Comment by Shadow403** [comment]
fixed https://github.com/Shadow403/nonebot_plugin_lolinfo/commit/2d602803055fdf6705971ab15817edb22d3a65a6
